spring.application.name=dsc

# Configuração do Banco de Dados H2 (em memória)
spring.datasource.url=jdbc:h2:mem:barberpro
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Chave secreta para assinatura dos tokens JWT
jwt.secret=minha-chave-secreta-super-longa-e-segura-para-o-barberpro
