spring.application.name=dsc

# Configuração para conectar ao Banco de Dados PostgreSQL no Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/barberpro
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Chave secreta para assinatura dos tokens JWT
jwt.secret=minha-chave-secreta-super-longa-e-segura-para-o-barberpro-com-mais-de-64-bytes-agora